### ISSUE TITLE
how to install on ubuntu?

### ISSUE THREAD

**Issue by pachadotdev** [claytonotey/libsbsms#8]
Hi!

Sorry if this is a basic question, but I tried the steps here https://preshing.com/20170511/how-to-build-a-cmake-based-project/ and I can't get it to work. How should I compile to put in `opt/bin` or any folder to use the noise removal and all the rest in Audacity?

I did this
```
~ $ git clone git@github.com:claytonotey/libsbsms.git
~ $ cd libsbsms
libsbsms (main) $ mkdir output
libsbsms (main) $ cmake --build output
Error: could not load cache
```

**Comment by SteveDaulton** [comment]
If you are just wanting to build Audacity, you don't need to build libsbsms separately as it is built by the Audacity build process.

**Comment by pachadotdev** [comment]
> 

thanks! I lost many options in Audacity because of this, I shall try to install audacity from source then
thanks a lot!!
